-- ====================================================================
-- JOBHUNTER - DROP TABLES (thu tu nguoc: con truoc, cha sau)
-- ====================================================================
USE JobHunterDB;
GO

IF OBJECT_ID('THEO_DOI_CONG_TY', 'U') IS NOT NULL DROP TABLE THEO_DOI_CONG_TY;
IF OBJECT_ID('TIN_YEU_THICH', 'U') IS NOT NULL DROP TABLE TIN_YEU_THICH;
IF OBJECT_ID('DON_UNG_TUYEN', 'U') IS NOT NULL DROP TABLE DON_UNG_TUYEN;
IF OBJECT_ID('TIN_KY_NANG', 'U') IS NOT NULL DROP TABLE TIN_KY_NANG;
IF OBJECT_ID('TIN_TUYEN_DUNG', 'U') IS NOT NULL DROP TABLE TIN_TUYEN_DUNG;
IF OBJECT_ID('CV_KY_NANG', 'U') IS NOT NULL DROP TABLE CV_KY_NANG;
IF OBJECT_ID('CV_HOC_VAN', 'U') IS NOT NULL DROP TABLE CV_HOC_VAN;
IF OBJECT_ID('CV_KINH_NGHIEM', 'U') IS NOT NULL DROP TABLE CV_KINH_NGHIEM;
IF OBJECT_ID('CV', 'U') IS NOT NULL DROP TABLE CV;
IF OBJECT_ID('NHA_TUYEN_DUNG', 'U') IS NOT NULL DROP TABLE NHA_TUYEN_DUNG;
IF OBJECT_ID('UNG_VIEN', 'U') IS NOT NULL DROP TABLE UNG_VIEN;
IF OBJECT_ID('THONG_BAO', 'U') IS NOT NULL DROP TABLE THONG_BAO;
IF OBJECT_ID('TOKEN_XAC_THUC', 'U') IS NOT NULL DROP TABLE TOKEN_XAC_THUC;
IF OBJECT_ID('DANH_MUC_NGANH_NGHE', 'U') IS NOT NULL DROP TABLE DANH_MUC_NGANH_NGHE;
IF OBJECT_ID('DANH_MUC_KY_NANG', 'U') IS NOT NULL DROP TABLE DANH_MUC_KY_NANG;
IF OBJECT_ID('THAM_SO', 'U') IS NOT NULL DROP TABLE THAM_SO;
IF OBJECT_ID('TAI_KHOAN', 'U') IS NOT NULL DROP TABLE TAI_KHOAN;
GO
